# FAÇA UM PROGRAMA QUE LEIA O PREÇO DE UM PRODUTO E MOSTRE SEU NOVO PREÇO COM
# 5% DE DESCONTO

preco = float(input("INSIRA O PREÇO DO PRODUTO: "))

print(f"O NOVO PREÇO, COM 5% DE DESCONTO É R$ {preco * 0.95:.2f}")
