# ESCREVA UM PROGRAMA QUE CONVERTA UMA TEMPERATURA DIGITADA EM °C E CONVERTA PARA °F

Tc = float(input("DIGITE A TEMPERATURA EM GRAUS CELSIUS: "))

print(f"{Tc}°C É EQUIVALENTE A {(Tc * 9 / 5) + 32}°F")
