# FAÇA UM ALGORITMO QUE LEIA O SALÁRIO DE UM FUNCIONÁRIO E MOSTRE SEU NOVO SALÁRIO, COM 15% DE AUMENTO

salario = float(input("DIGITE SEU SALÁRIO: "))

print(f"O NOVO SALÁRIO DO FUNCIONÁRIO É {salario*1.15:.2f}")
