# ESCREVA UM PROGRAMA QUE PERGUNTE A QUANTIDADE DE KMS PERCORRIDOS POR UM CARRO ALUGADO E A
# QUANTIDADE DE DIAS PELOS QUAIS ELE FOI ALUGADO. CALCULE O PREÇO A PAGAR SABENDO QUE O CARRO
# CUSTA R$ 60,00 POR DIA E R$ 0,15 POR KM/RODADO

dias = int(input("DIGITE A QUANTIDADE DE DIAS DE ALUGUEL: "))
km = float(input("DIGITE A QUANTIDADE DE KMS RODADOS: "))

print(f"O VALOR A SE PAGAR É R$ {dias*60 + 0.15*km}")
