# FAÇA UM PROGRAMA QUE LEIA O COMPRIMENTO DO CATETO OPOSTO E DO CATETO ADJACENTE DE UM TRIÂNGULO RETÂNGULO. CALCULE E MOSTRE O COMPRIMENTO DA HIPOTENUSA.

from math import *

cat_adj = float(input("DIGITE O COMPRIMENTO DO CATETO ADJACENTE: "))
cat_op = float(input("DIGITE O COMPRIMENTO DO CATETO OPOSTO: "))

print(f"O COMPRIMENTO DA HIPOTENUSA É: {sqrt((cat_adj**2) + (cat_op**2))}")
