# FAÇA UM PROGRAMA QUE LEIA A LARGURA E A ALTURA DE UMA PAREDE EM METROS,
# CALCULE A SUA ÁREA E A QUANTIDADE DE TINTA NECESSÁRIA PARA PINTÁ-LA, SABENDO
# QUE CADA LITRO DE TINTA PINTA UMA ÁREA DE 2 m²

larg = float(input("INSIRA A LARGURA DA PAREDE: "))
alt = float(input("INSIRA A ALTURA DA PAREDE: "))

area = larg * alt

print(f"A QUANTIDADE DE TINTA NECESSÁRIA É {area / 2} L")
