# ESCREVA UM PROGRAMA QUE LEIA UM VALOR EM METROS E O EXIBA CONVERTIDO EM CENTÍMETROS E MILÍMETROS

dist = float(input("DIGITE A DISTÂNCIA OU COMPRIMENTO EM METROS: "))

print(f"{dist} m CORRESPONDE A {dist*100} cm E {dist*1000} mm")
