# CRIE UM PROGRAMA QUE LEIA QUANTO DINHEIRO UMA PESSOA TEM NA CARTEIRA E MOSTRE QUANTOS DÓLARES ELA PODE COMPRAR
# CONSIDERE: U$1,00 = R$3,27

dindin = float(input("DIGITE A QUANTIDADE DE DINHEIRO: "))

print(f"R$ {dindin:.2f} É EQUIVALENTE À U$ {dindin / 3.27:.2f}")
